server {
      listen       80  ;
      server_name  netdata.local.z;
      location  / {
      proxy_pass  http://netdata:19999;
      }
}
server {
      listen       80  ;
      server_name  portainer.local.z;
      location  / {
      proxy_pass  http://portainer:9000;
      }
}
server {
      listen       80  ;
      server_name  beanstalkd-console.local.z;
      location  / {
      proxy_pass  http://beanstalkd-console:2080;
      }
}